### ISSUE TITLE
"Cannot read property 'lang' of undefined" when language is not English

### ISSUE THREAD

**Issue by AfikDeri** [iliyaZelenko/tiptap-vuetify#78]
In the latest vuetify release the way you access the current language is with:

```js
get vuetifyLang () {
    return this.vuetify.lang.current;
}
```

The way you do it in the `main.ts` file is:

```js
get vuetifyLang () {
    return this.vuetify.framework.lang.current
}
```

Which produces the following error:
![image](https://user-images.githubusercontent.com/17595033/67305526-261fce80-f4fe-11e9-90b9-583c04ae0122.png)

I'm not using english, the main language for my app is Hebrew (he).

Any idea on how to fix this?

Thanks.

**Comment by iliyaZelenko** [comment]
Hi, thanks for trying to use the package! I will be happy to help you.
Perhaps you are using version 1.x of Vuetify, not 2.x? I noticed that the description (`README.md`) was not the correct link to the version for 1.x. Now it is fixed:

> If you have Vuetify `1.x` (not `2.x`), then you can find docs and demo [here](https://github.com/iliyaZelenko/tiptap-vuetify/blob/version-1.x/README.md).

> For Vuetify 1.x use 1.x version of this package.
>
>```
>yarn add tiptap-vuetify@"^1.0.0"
># Or 
>npm install tiptap-vuetify@"^1.0.0"
>```

Sorry for the confusing documentation.

**Comment by AfikDeri** [comment]
@iliyaZelenko Thanks for the quick reply
I'm using Vuetify on version `2.1.5` and this component on the latest version.
I'm not sure why but I'm still getting this error.

Regardless, I made the Hebrew PR. check it out:
https://github.com/iliyaZelenko/tiptap-vuetify/pull/79

**Comment by iliyaZelenko** [comment]
@AfikDeri I guess what could be the problem. Could you please show the code that you are using, associated with [this](https://github.com/iliyaZelenko/tiptap-vuetify#npm-es-modules). What interests me most is what you pass as `vuetify` object.

``` js
Vue.use(TiptapVuetifyPlugin, {
  vuetify // <-- what do you pass here?
})
```

I wonder why other people did not create such a problem, and also everything works for me, look at this [example](https://codesandbox.io/s/tiptap-vuetify-wysiwyg-editor-6p9wp?fontsize=14), file `main.js`, everything should be like that.

**Comment by chrisborecki** [comment]
I have same issue, using vuetify@2.3.13
The error shows up when tiptap is using any extension.

TypeError: Cannot read property 'lang' of undefined
    at t.get [as vuetifyLang] (bundle-esm.js:1)
    at Sr (bundle-esm.js:1)
    at new t (bundle-esm.js:1)
    at Object.get [as availableActions] (bundle-esm.js:1)
    at bundle-esm.js:1
    at Array.forEach (<anonymous>)
    at VueComponent.n.mounted (bundle-esm.js:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at callHook (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
